apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app-2
  template:
    metadata:
      labels:
        app: web-app-2
    spec:
      containers:
        - name: web-app-2
          image: veenacr.azurecr.io/web-app-2:0.1.0
          ports:
            - containerPort: 80 
          env:
            - name: DefaultConnection
              value: "Data Source=tcp:az-cni-overlay.database.windows.net,1433;Initial Catalog=customer;User ID=azcnioverlay;Password=$ecr3t999"
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-2-service
spec:
  selector:
    app: web-app-2
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 20.232.4.220 #publicip of aks cluster
