apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app-2
  template:
    metadata:
      labels:
        app: web-app-2
    spec:
      containers:
        - name:web-app-2
          image: veenacr.azurecr.io/web-app-2:latest
          ports:
            - containerPort: 80
          env:
            - name: DefaultConnection
              value: "Server=tcp:customerdb.database.windows.net,1433;Initial Catalog=customerdb;Persist Security Info=False;User ID=saadmin;Password=$ecr3t999;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-2-service
spec:
  selector:
    app: web-app-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
